import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_storage/firebase_storage.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_typography.dart';
import '../../../core/constants/emotion_types.dart';
import '../../feed/models/post_model.dart';
import 'package:cached_network_image/cached_network_image.dart';

/// AURA Social – Create Post Screen (Connected to Firestore + Firebase Storage)
///
/// Text + image picker + optional mood expression.
/// Upload ảnh trực tiếp lên Firebase Storage, tạo post document trong Firestore.
class CreatePostScreen extends ConsumerStatefulWidget {
  final PostModel? postToEdit;
  const CreatePostScreen({super.key, this.postToEdit});
  @override
  ConsumerState<CreatePostScreen> createState() => _CreatePostScreenState();
}

class _CreatePostScreenState extends ConsumerState<CreatePostScreen> {
  final _contentCtrl = TextEditingController();
  String? _selectedMood;
  File? _pickedImage;
  String? _existingImageUrl;
  bool _isPosting = false;
  bool _isAssisting = false;

  @override
  void initState() {
    super.initState();
    if (widget.postToEdit != null) {
      _contentCtrl.text = widget.postToEdit!.content;
      _selectedMood = widget.postToEdit!.moodExpression;
      _existingImageUrl = widget.postToEdit!.mediaUrls.isNotEmpty
          ? widget.postToEdit!.mediaUrls.first
          : null;
    }
  }

  @override
  void dispose() {
    _contentCtrl.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final picked = await picker.pickImage(source: ImageSource.gallery, maxWidth: 1200, imageQuality: 85);
    if (picked != null) setState(() => _pickedImage = File(picked.path));
  }

  Future<void> _takePhoto() async {
    final picker = ImagePicker();
    final picked = await picker.pickImage(source: ImageSource.camera, maxWidth: 1200, imageQuality: 85);
    if (picked != null) setState(() => _pickedImage = File(picked.path));
  }

  Future<void> _createPost() async {
    if (_contentCtrl.text.trim().isEmpty) return;
    setState(() => _isPosting = true);

    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) return;

      // Lấy thông tin user để denormalize vào post
      final userDoc = await FirebaseFirestore.instance.collection('users').doc(user.uid).get();
      final userData = userDoc.data() ?? {};

      List<String> mediaUrls = [];
      String mediaType = 'none';

      // Upload ảnh lên Firebase Storage trực tiếp (giống chat)
      if (_pickedImage != null) {
        try {
          final fileName = '${DateTime.now().millisecondsSinceEpoch}_${user.uid}.jpg';
          final storageRef = FirebaseStorage.instance
              .ref()
              .child('posts/$fileName');
          final uploadTask = storageRef.putFile(
            _pickedImage!,
            SettableMetadata(contentType: 'image/jpeg'),
          );
          final snapshot = await uploadTask;
          final url = await snapshot.ref.getDownloadURL();
          mediaUrls = [url];
          mediaType = 'image';
          debugPrint('[CreatePost] Upload success, URL: $url');
        } catch (e) {
          debugPrint('[CreatePost] Upload exception: $e');
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(
              content: Text('⚠️ Upload ảnh thất bại: $e'),
              backgroundColor: AuraColors.warning,
              behavior: SnackBarBehavior.floating,
            ));
          }
          // Fallback: post without image
        }
      } else if (_existingImageUrl != null) {
        mediaUrls = [_existingImageUrl!];
        mediaType = widget.postToEdit!.mediaType;
      }

      if (widget.postToEdit != null) {
        // Cập nhật post document
        await FirebaseFirestore.instance.collection('posts').doc(widget.postToEdit!.postId).update({
          'content': _contentCtrl.text.trim(),
          'media_urls': mediaUrls,
          'media_type': mediaType,
          'mood_expression': _selectedMood,
          'updated_at': FieldValue.serverTimestamp(),
        });
      } else {
        // Tạo post document mới
        final post = PostModel(
          postId: '', // auto-generated by Firestore
          userId: user.uid,
          content: _contentCtrl.text.trim(),
          mediaUrls: mediaUrls,
          mediaType: mediaType,
          moodExpression: _selectedMood,
          authorName: userData['display_name'] ?? user.displayName ?? '',
          authorUsername: userData['username'] ?? '',
          authorAvatarUrl: userData['avatar_url'],
          authorDominantEmotion: userData['aura_dominant_emotion'],
        );

        await FirebaseFirestore.instance.collection('posts').add(post.toFirestore());

        // Update post count
        await FirebaseFirestore.instance.collection('users').doc(user.uid).set({
          'posts_count': FieldValue.increment(1),
        }, SetOptions(merge: true));
      }

      if (mounted) context.pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text('Lỗi: $e'), backgroundColor: AuraColors.error));
      }
    } finally {
      if (mounted) setState(() => _isPosting = false);
    }
  }

  Future<void> _runAiAssist() async {
    final text = _contentCtrl.text.trim();
    final mood = _selectedMood ?? 'joy';

    setState(() => _isAssisting = true);

    try {
      final response = await ref.read(apiServiceProvider).post('/api/v1/content/assist', data: {
        'text': text,
        'mood_theme': mood,
      });

      final data = response.data;
      final suggestions = List<String>.from(data['suggestions'] ?? []);
      final emotions = Map<String, dynamic>.from(data['predicted_emotion_vector'] ?? {}).map(
        (k, v) => MapEntry(k, (v as num).toDouble()),
      );

      if (mounted) {
        _showAssistSuggestionsSheet(suggestions, emotions);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text('Lỗi trợ lý AI: $e'),
          backgroundColor: AuraColors.error,
        ));
      }
    } finally {
      if (mounted) setState(() => _isAssisting = false);
    }
  }

  void _showAssistSuggestionsSheet(List<String> suggestions, Map<String, double> emotions) {
    final topEmotions = emotions.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    final dominant = topEmotions.isNotEmpty ? topEmotions.first.key : 'joy';
    final confidence = topEmotions.isNotEmpty ? topEmotions.first.value : 0.0;

    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      builder: (context) => DraggableScrollableSheet(
        initialChildSize: 0.6,
        maxChildSize: 0.9,
        builder: (_, scrollController) => Container(
          decoration: BoxDecoration(
            color: AuraColors.surface,
            borderRadius: const BorderRadius.vertical(top: Radius.circular(24)),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
          child: Column(
            children: [
              Container(
                width: 40,
                height: 4,
                decoration: BoxDecoration(
                  color: AuraColors.surfaceBorder,
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
              const SizedBox(height: 16),
              Text(
                '✨ Trợ Lý Sáng Tạo AURA',
                style: AuraTypography.titleMedium.copyWith(
                  color: AuraColors.textPrimary,
                  fontWeight: FontWeight.w800,
                ),
              ),
              const SizedBox(height: 12),
              
              // Emotion Preview Banner
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: AuraColors.getEmotionColor(dominant).withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(
                    color: AuraColors.getEmotionColor(dominant).withValues(alpha: 0.3),
                  ),
                ),
                child: Row(
                  children: [
                    Icon(Icons.psychology_outlined, size: 24, color: AuraColors.getEmotionColor(dominant)),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Dự đoán cảm xúc bài viết',
                            style: AuraTypography.labelMedium.copyWith(
                              color: AuraColors.textPrimary,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                          Text(
                            'Cảm xúc chủ đạo dự kiến: ${dominant.toUpperCase()} (${(confidence * 100).round()}%). Vui lòng chọn gợi ý bên dưới để thay đổi.',
                            style: AuraTypography.bodySmall.copyWith(
                              color: AuraColors.textSecondary,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 16),
              
              Expanded(
                child: ListView(
                  controller: scrollController,
                  children: [
                    Text(
                      'Gợi ý viết bài từ AI:',
                      style: AuraTypography.labelMedium.copyWith(color: AuraColors.textTertiary),
                    ),
                    const SizedBox(height: 10),
                    ...suggestions.map((s) => Padding(
                      padding: const EdgeInsets.only(bottom: 12),
                      child: InkWell(
                        onTap: () {
                          _contentCtrl.text = s;
                          Navigator.pop(context);
                        },
                        borderRadius: BorderRadius.circular(12),
                        child: Container(
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                            color: AuraColors.surfaceVariant,
                            borderRadius: BorderRadius.circular(12),
                            border: Border.all(
                              color: AuraColors.surfaceBorder,
                              width: 0.8,
                            ),
                          ),
                          child: Text(
                            s,
                            style: AuraTypography.bodyMedium.copyWith(
                              color: AuraColors.textPrimary,
                              height: 1.4,
                            ),
                          ),
                        ),
                      ),
                    )),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final hasContent = _contentCtrl.text.trim().isNotEmpty;

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(icon: const Icon(Icons.close_rounded), onPressed: () => Navigator.of(context).pop()),
        title: Text(widget.postToEdit != null ? 'Chỉnh sửa bài viết' : 'Bài viết mới'),
        actions: [
          Padding(padding: const EdgeInsets.only(right: 12),
            child: FilledButton(
              onPressed: (hasContent && !_isPosting) ? _createPost : null,
              style: FilledButton.styleFrom(padding: const EdgeInsets.symmetric(horizontal: 20), minimumSize: const Size(0, 36)),
              child: _isPosting
                ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                : Text(widget.postToEdit != null ? 'Lưu' : 'Đăng'),
            )),
        ],
      ),
      body: Column(children: [
        Expanded(child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            TextField(
              controller: _contentCtrl, maxLines: null, minLines: 5, enabled: !_isPosting,
              style: AuraTypography.bodyLarge.copyWith(color: AuraColors.textPrimary),
              decoration: InputDecoration(hintText: 'Bạn đang nghĩ gì?...', border: InputBorder.none, enabledBorder: InputBorder.none, focusedBorder: InputBorder.none, filled: false,
                hintStyle: AuraTypography.bodyLarge.copyWith(color: AuraColors.textTertiary)),
              onChanged: (_) => setState(() {}),
            ),
            // Ảnh đã chọn
            if (_pickedImage != null) ...[
              const SizedBox(height: 12),
              Stack(children: [
                ClipRRect(borderRadius: BorderRadius.circular(12),
                  child: Image.file(_pickedImage!, width: double.infinity, height: 200, fit: BoxFit.cover)),
                Positioned(top: 8, right: 8, child: GestureDetector(
                  onTap: () => setState(() => _pickedImage = null),
                  child: Container(padding: const EdgeInsets.all(4), decoration: const BoxDecoration(color: Colors.black54, shape: BoxShape.circle),
                    child: const Icon(Icons.close, color: Colors.white, size: 18)),
                )),
              ]),
            ] else if (_existingImageUrl != null) ...[
              const SizedBox(height: 12),
              Stack(children: [
                ClipRRect(borderRadius: BorderRadius.circular(12),
                  child: CachedNetworkImage(
                    imageUrl: _existingImageUrl!,
                    width: double.infinity,
                    height: 200,
                    fit: BoxFit.cover,
                    placeholder: (_, __) => Container(
                      color: AuraColors.surfaceVariant,
                      child: Center(
                        child: CircularProgressIndicator(strokeWidth: 2, color: AuraColors.primary),
                      ),
                    ),
                    errorWidget: (_, __, ___) => Container(
                      color: AuraColors.surfaceVariant,
                      child: Icon(Icons.image_not_supported_outlined, color: AuraColors.textTertiary, size: 40),
                    ),
                  )),
                Positioned(top: 8, right: 8, child: GestureDetector(
                  onTap: () => setState(() => _existingImageUrl = null),
                  child: Container(padding: const EdgeInsets.all(4), decoration: const BoxDecoration(color: Colors.black54, shape: BoxShape.circle),
                    child: const Icon(Icons.close, color: Colors.white, size: 18)),
                )),
              ]),
            ],
          ]),
        )),
        // Bottom toolbar
        Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(color: AuraColors.surface, border: Border(top: BorderSide(color: AuraColors.surfaceBorder, width: .5))),
          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text('Cảm xúc (tùy chọn)', style: AuraTypography.labelMedium.copyWith(color: AuraColors.textTertiary)),
            const SizedBox(height: 10),
            SingleChildScrollView(scrollDirection: Axis.horizontal, child: Row(
              children: EmotionType.values.map((e) {
                final sel = _selectedMood == e.key;
                return Padding(padding: const EdgeInsets.only(right: 8), child: GestureDetector(
                  onTap: () => setState(() => _selectedMood = sel ? null : e.key),
                  child: AnimatedContainer(duration: const Duration(milliseconds: 200),
                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                    decoration: BoxDecoration(
                      color: sel ? AuraColors.getEmotionColor(e.key).withValues(alpha: .15) : AuraColors.surfaceVariant,
                      borderRadius: BorderRadius.circular(24),
                      border: sel ? Border.all(color: AuraColors.getEmotionColor(e.key).withValues(alpha: .5)) : Border.all(color: AuraColors.surfaceBorder, width: .5)),
                    child: Row(mainAxisSize: MainAxisSize.min, children: [
                      Text(e.emoji, style: const TextStyle(fontSize: 18)),
                      const SizedBox(width: 6),
                      Text(e.labelVi, style: AuraTypography.labelSmall.copyWith(
                        color: sel ? AuraColors.getEmotionColor(e.key) : AuraColors.textSecondary,
                        fontWeight: sel ? FontWeight.w600 : FontWeight.w400)),
                    ]),
                  ),
                ));
              }).toList(),
            )),
            const SizedBox(height: 12),
            Row(children: [
              _ToolBtn(icon: Icons.image_outlined, label: 'Thư viện', onTap: _isPosting ? null : _pickImage),
              const SizedBox(width: 12),
              _ToolBtn(icon: Icons.camera_alt_outlined, label: 'Chụp ảnh', onTap: _isPosting ? null : _takePhoto),
              const SizedBox(width: 12),
              _ToolBtn(
                icon: Icons.auto_awesome_outlined,
                label: _isAssisting ? 'Đang phân tích...' : 'Gợi ý AI',
                onTap: (_isPosting || _isAssisting) ? null : _runAiAssist,
              ),
            ]),
          ]),
        ),
      ]),
    );
  }
}

class _ToolBtn extends StatelessWidget {
  const _ToolBtn({required this.icon, required this.label, this.onTap});
  final IconData icon; final String label; final VoidCallback? onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(onTap: onTap, child: Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(color: AuraColors.surfaceVariant, borderRadius: BorderRadius.circular(10)),
      child: Row(children: [
        Icon(icon, size: 18, color: AuraColors.primary),
        const SizedBox(width: 6),
        Text(label, style: AuraTypography.labelSmall.copyWith(color: AuraColors.textSecondary)),
      ]),
    ));
  }
}
