import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_typography.dart';
import '../../../core/constants/emotion_types.dart';
import '../../../providers/api_service_provider.dart';
import '../../../providers/user_profile_provider.dart';
import '../../feed/models/post_model.dart';

/// AURA Social – Create Post Screen (Connected to Firestore + R2 upload)
///
/// Text + image picker + optional mood expression.
/// Upload ảnh qua FastAPI → R2, tạo post document trong Firestore.
class CreatePostScreen extends ConsumerStatefulWidget {
  const CreatePostScreen({super.key});
  @override
  ConsumerState<CreatePostScreen> createState() => _CreatePostScreenState();
}

class _CreatePostScreenState extends ConsumerState<CreatePostScreen> {
  final _contentCtrl = TextEditingController();
  String? _selectedMood;
  File? _pickedImage;
  bool _isPosting = false;

  @override
  void dispose() {
    _contentCtrl.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final picked = await picker.pickImage(source: ImageSource.gallery, maxWidth: 1200, imageQuality: 85);
    if (picked != null) setState(() => _pickedImage = File(picked.path));
  }

  Future<void> _takePhoto() async {
    final picker = ImagePicker();
    final picked = await picker.pickImage(source: ImageSource.camera, maxWidth: 1200, imageQuality: 85);
    if (picked != null) setState(() => _pickedImage = File(picked.path));
  }

  Future<void> _createPost() async {
    if (_contentCtrl.text.trim().isEmpty) return;
    setState(() => _isPosting = true);

    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) return;

      // Lấy thông tin user để denormalize vào post
      final userDoc = await FirebaseFirestore.instance.collection('users').doc(user.uid).get();
      final userData = userDoc.data() ?? {};

      List<String> mediaUrls = [];
      String mediaType = 'none';

      // Upload ảnh qua FastAPI → R2 (nếu có)
      if (_pickedImage != null) {
        try {
          final api = ref.read(apiServiceProvider);
          final response = await api.uploadFile(
            '/api/v1/upload/image',
            filePath: _pickedImage!.path,
            fieldName: 'file',
            extraFields: {'type': 'post'},
          );
          if (response.statusCode == 200) {
            mediaUrls = [response.data['url']];
            mediaType = 'image';
          }
        } catch (e) {
          debugPrint('[CreatePost] Upload failed: $e');
          // Fallback: post without image
        }
      }

      // Tạo post document
      final post = PostModel(
        postId: '', // auto-generated by Firestore
        userId: user.uid,
        content: _contentCtrl.text.trim(),
        mediaUrls: mediaUrls,
        mediaType: mediaType,
        moodExpression: _selectedMood,
        authorName: userData['display_name'] ?? user.displayName ?? '',
        authorUsername: userData['username'] ?? '',
        authorAvatarUrl: userData['avatar_url'],
        authorDominantEmotion: userData['aura_dominant_emotion'],
      );

      await FirebaseFirestore.instance.collection('posts').add(post.toFirestore());

      // Update post count
      await FirebaseFirestore.instance.collection('users').doc(user.uid).update({
        'posts_count': FieldValue.increment(1),
      });

      if (mounted) context.pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text('Lỗi tạo bài viết: $e'), backgroundColor: AuraColors.error));
      }
    } finally {
      if (mounted) setState(() => _isPosting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final hasContent = _contentCtrl.text.trim().isNotEmpty;

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(icon: const Icon(Icons.close_rounded), onPressed: () => Navigator.of(context).pop()),
        title: const Text('Bài viết mới'),
        actions: [
          Padding(padding: const EdgeInsets.only(right: 12),
            child: FilledButton(
              onPressed: (hasContent && !_isPosting) ? _createPost : null,
              style: FilledButton.styleFrom(padding: const EdgeInsets.symmetric(horizontal: 20), minimumSize: const Size(0, 36)),
              child: _isPosting
                ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                : const Text('Đăng'),
            )),
        ],
      ),
      body: Column(children: [
        Expanded(child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            TextField(
              controller: _contentCtrl, maxLines: null, minLines: 5, enabled: !_isPosting,
              style: AuraTypography.bodyLarge.copyWith(color: AuraColors.textPrimary),
              decoration: InputDecoration(hintText: 'Bạn đang nghĩ gì?...', border: InputBorder.none, enabledBorder: InputBorder.none, focusedBorder: InputBorder.none, filled: false,
                hintStyle: AuraTypography.bodyLarge.copyWith(color: AuraColors.textTertiary)),
              onChanged: (_) => setState(() {}),
            ),
            // Ảnh đã chọn
            if (_pickedImage != null) ...[
              const SizedBox(height: 12),
              Stack(children: [
                ClipRRect(borderRadius: BorderRadius.circular(12),
                  child: Image.file(_pickedImage!, width: double.infinity, height: 200, fit: BoxFit.cover)),
                Positioned(top: 8, right: 8, child: GestureDetector(
                  onTap: () => setState(() => _pickedImage = null),
                  child: Container(padding: const EdgeInsets.all(4), decoration: BoxDecoration(color: Colors.black54, shape: BoxShape.circle),
                    child: const Icon(Icons.close, color: Colors.white, size: 18)),
                )),
              ]),
            ],
          ]),
        )),
        // Bottom toolbar
        Container(
          padding: const EdgeInsets.all(16),
          decoration: const BoxDecoration(color: AuraColors.surface, border: Border(top: BorderSide(color: AuraColors.surfaceBorder, width: .5))),
          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text('Cảm xúc (tùy chọn)', style: AuraTypography.labelMedium.copyWith(color: AuraColors.textTertiary)),
            const SizedBox(height: 10),
            SingleChildScrollView(scrollDirection: Axis.horizontal, child: Row(
              children: EmotionType.values.map((e) {
                final sel = _selectedMood == e.key;
                return Padding(padding: const EdgeInsets.only(right: 8), child: GestureDetector(
                  onTap: () => setState(() => _selectedMood = sel ? null : e.key),
                  child: AnimatedContainer(duration: const Duration(milliseconds: 200),
                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                    decoration: BoxDecoration(
                      color: sel ? AuraColors.getEmotionColor(e.key).withValues(alpha: .15) : AuraColors.surfaceVariant,
                      borderRadius: BorderRadius.circular(24),
                      border: sel ? Border.all(color: AuraColors.getEmotionColor(e.key).withValues(alpha: .5)) : Border.all(color: AuraColors.surfaceBorder, width: .5)),
                    child: Row(mainAxisSize: MainAxisSize.min, children: [
                      Text(e.emoji, style: const TextStyle(fontSize: 18)),
                      const SizedBox(width: 6),
                      Text(e.labelVi, style: AuraTypography.labelSmall.copyWith(
                        color: sel ? AuraColors.getEmotionColor(e.key) : AuraColors.textSecondary,
                        fontWeight: sel ? FontWeight.w600 : FontWeight.w400)),
                    ]),
                  ),
                ));
              }).toList(),
            )),
            const SizedBox(height: 12),
            Row(children: [
              _ToolBtn(icon: Icons.image_outlined, label: 'Thư viện', onTap: _isPosting ? null : _pickImage),
              const SizedBox(width: 12),
              _ToolBtn(icon: Icons.camera_alt_outlined, label: 'Chụp ảnh', onTap: _isPosting ? null : _takePhoto),
            ]),
          ]),
        ),
      ]),
    );
  }
}

class _ToolBtn extends StatelessWidget {
  const _ToolBtn({required this.icon, required this.label, this.onTap});
  final IconData icon; final String label; final VoidCallback? onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(onTap: onTap, child: Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(color: AuraColors.surfaceVariant, borderRadius: BorderRadius.circular(10)),
      child: Row(children: [
        Icon(icon, size: 18, color: AuraColors.primary),
        const SizedBox(width: 6),
        Text(label, style: AuraTypography.labelSmall.copyWith(color: AuraColors.textSecondary)),
      ]),
    ));
  }
}
