// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7NpEKGb6rY8R9bgXRw1PWVPEXmfmhr0A',
    appId: '1:736756685022:web:626944cea7716eae250a4f',
    messagingSenderId: '736756685022',
    projectId: 'aura-social-vn',
    authDomain: 'aura-social-vn.firebaseapp.com',
    databaseURL: 'https://aura-social-vn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-social-vn.firebasestorage.app',
    measurementId: 'G-8JS8FXCB35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPreZzsIp-0uSOmyyZmI0Egx68zZpr-Fs',
    appId: '1:736756685022:android:b74a07787ab9a449250a4f',
    messagingSenderId: '736756685022',
    projectId: 'aura-social-vn',
    databaseURL: 'https://aura-social-vn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-social-vn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZghid43W8gFPWZ_fkSieXgAEhYcHETzw',
    appId: '1:736756685022:ios:58376c3b3f3aaf5e250a4f',
    messagingSenderId: '736756685022',
    projectId: 'aura-social-vn',
    databaseURL: 'https://aura-social-vn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-social-vn.firebasestorage.app',
    iosClientId: '736756685022-0pe71pmm15o87ofijbtbpfc4rjkeisj2.apps.googleusercontent.com',
    iosBundleId: 'com.aurasocial.app',
  );
}
